[workspace]
members = [
    # Binaries
    "src/binaries",
    # Common
    "src/common/arrow",
    "src/common/base",
    "src/common/building",
    "src/common/cache",
    "src/common/contexts",
    "src/common/exception",
    "src/common/grpc",
    "src/common/hashtable",
    "src/common/http",
    "src/common/io",
    "src/common/macros",
    "src/common/metrics",
    "src/common/tracing",
    "src/common/storage",
    # Query
    "src/query/ast",
    "src/query/codegen",
    "src/query/config",
    "src/query/catalog",
    "src/query/datablocks",
    "src/query/datavalues",
    "src/query/expression",
    "src/query/formats",
    "src/query/functions",
    "src/query/functions-v2",
    "src/query/legacy-parser",
    "src/query/management",
    "src/query/planner",
    "src/query/pipeline/core",
    "src/query/pipeline/sinks",
    "src/query/pipeline/sources",
    "src/query/pipeline/transforms",
    "src/query/legacy-planners",
    "src/query/settings",
    "src/query/storages/fuse",
    "src/query/storages/fuse-meta",
    "src/query/storages/hive",
    "src/query/storages/hive-meta-store",
    "src/query/storages/index",
    "src/query/storages/preludes",
    "src/query/storages/share",
    "src/query/storages/util",
    "src/query/streams",
    "src/query/users",
    # databend-query
    "src/query/service",
    # Meta
    "src/meta/api",
    "src/meta/app",
    "src/meta/embedded",
    "src/meta/raft-store",
    "src/meta/sled-store",
    "src/meta/store",
    "src/meta/types",
    # meta proto
    "src/meta/proto-conv",
    "src/meta/protos",
    # databend-meta
    "src/meta/service",
    # Hack
    # This crate is used to hack our cargo.lock to resovle CVEs and so on.
    "src/workspace-hack",
]

[profile.release]
debug = 1
lto = "thin"
overflow-checks = false
codegen-units = 1       # Reduce number of codegen units to increase optimizations.

[profile.release.package]
arrow2 = { codegen-units = 4 }
common-functions = { codegen-units = 16 }
databend-query = { codegen-units = 4 }

[profile.bench]
debug = true
overflow-checks = false

[profile.dev]
split-debuginfo = "unpacked"
overflow-checks = false

[profile.test]
opt-level = 0
debug = 0
codegen-units = 16
lto = false
incremental = true
debug-assertions = true
overflow-checks = true
rpath = false

[profile.dev.package]
addr2line = { opt-level = 3 }
adler = { opt-level = 3 }
gimli = { opt-level = 3 }
miniz_oxide = { opt-level = 3 }
object = { opt-level = 3 }
rustc-demangle = { opt-level = 3 }

[patch.crates-io]
# http-types doesn't play well with the new errors api.
# This fork address this problem, and should be removed once we upgrade to
# new toolchain.
http-types = { git = "https://github.com/Xuanwo/http-types", rev = "106fc6d" }
