name: "Publish Binary"
description: "Publish releases binaries"
inputs:
  github_token:
    description: "Github token"
    required: true
  version:
    description: "Release version"
    required: true
  target:
    description: "Release target"
    required: true
  repo_role_arn:
    description: "Repo Role Arn"
    required: true
  mode:
    description: "Release Normal / Hive"
    required: false
    default: normal

runs:
  using: "composite"
  steps:
    - name: Update normal release to github
      shell: bash
      # Reference: https://cli.github.com/manual/gh_release_upload
      if: inputs.mode == 'normal'
      run: gh release upload ${{ inputs.version }} databend-${{ inputs.version }}-${{ inputs.target }}.* --clobber
      env:
        GH_TOKEN: ${{ inputs.github_token }}

    - name: Update hive release to github
      shell: bash
      if: inputs.mode == 'hive'
      run: gh release upload ${{ inputs.version }} databend-hive-${{ inputs.version }}-${{ inputs.target }}.* --clobber
      env:
        GH_TOKEN: ${{ inputs.github_token }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-duration-seconds: 900
        role-to-assume: ${{ inputs.repo_role_arn }}
        aws-region: us-east-2

    - name: Sync normal release to S3
      shell: bash
      if: inputs.mode == 'normal'
      run: |
        aws s3 cp databend-${{ inputs.version }}-${{ inputs.target }}.tar.gz s3://repo.databend.rs/databend/${{ inputs.version }}/databend-${{ inputs.version }}-${{ inputs.target }}.tar.gz
        curl --retry 3 -fsSLo tags.json \
            --header 'content-type: application/json' \
            --header 'authorization: Bearer ${{ inputs.github_token }}' \
            https://api.github.com/repos/datafuselabs/databend/tags
        cat tags.json
        aws s3 cp ./tags.json s3://repo.databend.rs/databend/tags.json
        curl --retry 3 -fsSLo releases.json \
            --header 'content-type: application/json' \
            --header 'authorization: Bearer ${{ inputs.github_token }}' \
            https://api.github.com/repos/datafuselabs/databend/releases
        cat releases.json
        aws s3 cp ./releases.json s3://repo.databend.rs/databend/releases.json

    - name: Sync hive release to S3
      shell: bash
      if: inputs.mode == 'hive'
      run: |
        aws s3 cp databend-hive-${{ inputs.version }}-${{ inputs.target }}.tar.gz s3://repo.databend.rs/databend/${{ inputs.version }}/databend-hive-${{ inputs.version }}-${{ inputs.target }}.tar.gz
        curl --retry 3 -fsSLo tags.json \
            --header 'content-type: application/json' \
            --header 'authorization: Bearer ${{ inputs.github_token }}' \
            https://api.github.com/repos/datafuselabs/databend/tags
        cat tags.json
        aws s3 cp ./tags.json s3://repo.databend.rs/databend/tags.json
        curl --retry 3 -fsSLo releases.json \
            --header 'content-type: application/json' \
            --header 'authorization: Bearer ${{ inputs.github_token }}' \
            https://api.github.com/repos/datafuselabs/databend/releases
        cat releases.json
        aws s3 cp ./releases.json s3://repo.databend.rs/databend/releases.json
