[package]
name = "common-planner"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
common-catalog = { path = "../catalog" }
common-datavalues = { path = "../datavalues" }

parking_lot = "0.12"
