[package]
name = "common-contexts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../base" }

async-trait = "0.1.56"
opendal = { git = "https://github.com/sundy-li/opendal", rev = "a1f69bc", features = ["retry"] }
time = "0.3.10"
