[package]
name = "common-config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../base" }
common-exception = { path = "../exception" }
common-grpc = { path = "../grpc" }
common-hive-meta-store = { path = "../hive-meta-store", optional = true }
common-storage = { path = "../storage" }
common-tracing = { path = "../tracing" }

async-trait = "0.1.56"
clap = { version = "3.2.5", features = ["derive", "env"] }
once_cell = "1.12.0"
opendal = { git = "https://github.com/sundy-li/opendal", rev = "a1f69bc", features = ["retry", "compress"] }
semver = "1.0.10"
serde = { version = "1.0.137", features = ["derive"] }
serfig = "0.0.2"
thrift = { version = "0.15.0", optional = true }
time = "0.3.10"

[features]
default = []
storage-hdfs = ["opendal/services-hdfs", "common-storage/storage-hdfs"]
hive = ["common-hive-meta-store", "thrift", "storage-hdfs"]
