[package]
authors = ["Databend Authors <opensource@datafuselabs.com>"]
edition = "2021"
license = "Apache-2.0"
name = "common-arrow"
publish = false
version = "0.1.0"

[lib]
doctest = false
test = false

[features]
arrow-default = [
    "arrow/compute",
    "arrow/regex",
    "arrow/io_csv",
    "arrow/io_parquet",
    "arrow/io_json",
    "arrow/io_flight",
    "arrow/compute_filter",
]
default = ["arrow-default", "parquet-default"]
parquet-default = [
    "parquet2/lz4",
    "parquet2/zstd",
    "parquet2/snappy",
    "parquet2/gzip_zlib_ng",
    "parquet2/brotli",
]
simd = ["arrow/simd"]

[dependencies] # In alphabetical order
# Workspace dependencies

# Crates.io dependencies
# arrow = { package = "arrow2", path = "/home/sundy/work/arrow2", default-features = false, features = [
#     "io_parquet",
#     "io_fuse",
#     "io_parquet_compression",
# ] }

arrow = { package = "arrow2", git = "https://github.com/sundy-li/arrow2", rev = "02247bccc7", default-features = false, features = [
    "io_parquet",
    "io_fuse",
    "io_parquet_compression",
] }

arrow-format = { version = "0.8.0", features = ["flight-data", "flight-service", "ipc"] }
futures = "0.3.24"
parquet2 = { version = "0.17.0", default_features = false }

[dev-dependencies]
