[package]
name = "common-storages-hive"
version = "0.1.0"
edition = "2021"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-arrow = { path = "../../../../common/arrow" }
common-base = { path = "../../../../common/base" }
common-catalog = { path = "../../../catalog" }
common-exception = { path = "../../../../common/exception" }
common-expression = { path = "../../../expression" }
common-functions = { path = "../../../functions" }
common-hive-meta-store = { path = "../hive-meta-store" }
common-meta-app = { path = "../../../../meta/app" }
common-meta-types = { path = "../../../../meta/types" }
common-pipeline-core = { path = "../../../pipeline/core" }
common-pipeline-sources = { path = "../../../pipeline/sources" }
common-sql = { path = "../../../sql" }
common-storage = { path = "../../../../common/storage" }

storages-common-cache = { path = "../../common/cache" }
storages-common-cache-manager = { path = "../../common/cache-manager" }
storages-common-index = { path = "../../common/index" }
storages-common-table-meta = { path = "../../common/table-meta" }

async-recursion = "1.0.0"
async-trait = "0.1.57"
chrono = { workspace = true }
futures = "0.3.24"
opendal = { workspace = true }
ordered-float = { workspace = true }
serde = { workspace = true }
thrift = { package = "databend-thrift", version = "0.17.0" }
tracing = "0.1.36"
typetag = "0.2.3"
