[package]
name = "common-storages-fuse"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = true

[features]
enable-histogram-metrics = ["metrics/enable-histogram", "storages-common-cache/enable-histogram-metrics"]

[dependencies]
common-arrow = { path = "../../../common/arrow" }
common-base = { path = "../../../common/base" }
common-catalog = { path = "../../catalog" }
common-exception = { path = "../../../common/exception" }
common-expression = { path = "../../expression" }
common-functions = { path = "../../functions" }
common-io = { path = "../../../common/io" }
common-meta-app = { path = "../../../meta/app" }
common-meta-types = { path = "../../../meta/types" }
common-pipeline-core = { path = "../../pipeline/core" }
common-pipeline-sources = { path = "../../pipeline/sources" }
common-pipeline-transforms = { path = "../../pipeline/transforms" }
common-sharing = { path = "../../sharing" }
common-sql = { path = "../../sql" }
common-storage = { path = "../../../common/storage" }
jsonb = { workspace = true }

storages-common-blocks = { path = "../common/blocks" }
storages-common-cache = { path = "../common/cache" }
storages-common-cache-manager = { path = "../common/cache-manager" }
storages-common-index = { path = "../common/index" }
storages-common-pruner = { path = "../common/pruner" }
storages-common-table-meta = { path = "../common/table-meta" }

async-trait = { version = "0.1.57", package = "async-trait-fn" }
backoff = { version = "0.4.0", features = ["futures", "tokio"] }
chrono = { workspace = true }
futures = "0.3.24"
futures-util = "0.3.24"
metrics = "0.20.1"
opendal = { workspace = true }
rand = "0.8"
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.10.6"
siphasher = "0.3.10"
streaming-decompression = "0.1.2"
tokio-rayon = "2.1.0"
tracing = "0.1.36"
typetag = "0.2.3"
uuid = { version = "1.1.2", features = ["serde", "v4"] }
