[package]
name = "databend-query"
version = "0.1.0"
description = "A real-time Cloud Distributed Query Engine"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[[bin]]
name = "databend-query"
path = "bin/databend-query.rs"
doctest = false
test = false

[features]
default = ["simd"]
simd = ["common-arrow/simd"]
tokio-console = ["common-tracing/console", "common-base/tracing"]
memory-profiling = ["common-base/memory-profiling", "common-http/memory-profiling", "tempfile"]
storage-hdfs = ["opendal/services-hdfs", "common-storage/storage-hdfs"]
hive = ["common-hive-meta-store", "thrift", "storage-hdfs", "common-config/hive"]
io-uring = [
    "common-meta-embedded/io-uring",
    "common-meta-store/io-uring",
    "common-meta-sled-store/io-uring",
    "common-meta-raft-store/io-uring",
]

[dependencies]
# Workspace dependencies
common-arrow = { path = "../common/arrow" }
common-ast = { path = "../common/ast" }
common-base = { path = "../common/base" }
common-cache = { path = "../common/cache" }
common-catalog = { path = "../common/catalog" }
common-config = { path = "../common/config" }
common-contexts = { path = "../common/contexts" }
common-datablocks = { path = "../common/datablocks" }
common-datavalues = { path = "../common/datavalues" }
common-exception = { path = "../common/exception" }
common-formats = { path = "../common/formats" }
common-functions = { path = "../common/functions" }
common-fuse-meta = { path = "../common/fuse-meta" }
common-grpc = { path = "../common/grpc" }
common-hashtable = { path = "../common/hashtable" }
common-hive-meta-store = { path = "../common/hive-meta-store", optional = true }
common-http = { path = "../common/http" }
common-io = { path = "../common/io" }
common-macros = { path = "../common/macros" }
common-management = { path = "../common/management" }
common-meta-api = { path = "../common/meta/api" }
common-meta-app = { path = "../common/meta/app" }
common-meta-embedded = { path = "../common/meta/embedded" }
common-meta-grpc = { path = "../common/meta/grpc" }
common-meta-raft-store = { path = "../common/meta/raft-store" }
common-meta-sled-store = { path = "../common/meta/sled-store" }
common-meta-store = { path = "../common/meta/store" }
common-meta-types = { path = "../common/meta/types" }
common-metrics = { path = "../common/metrics" }
common-pipeline = { path = "../common/pipeline" }
common-planners = { path = "../common/planners" }
common-settings = { path = "../common/settings" }
common-storage = { path = "../common/storage" }
common-streams = { path = "../common/streams" }
common-tracing = { path = "../common/tracing" }
common-users = { path = "../common/users" }

# Github dependencies
async-trait = { git = "https://github.com/datafuse-extras/async-trait", rev = "f0b0fd5" }
sqlparser = { git = "https://github.com/datafuse-extras/sqlparser-rs", rev = "7f246e3" }

# Crates.io dependencies
ahash = "0.7.6"
async-channel = "1.6.1"
async-compat = "0.2.1"
async-recursion = "1.0.0"
async-stream = "0.3.3"
backoff = { version = "0.4.0", features = ["futures", "tokio"] }
backon = "0.0.2"
base64 = "0.13.0"
bincode = "2.0.0-rc.1"
bit-vec = { version = "0.6.3", features = ["serde_std"] }
bumpalo = "3.10.0"
byteorder = "1.4.3"
bytes = "1.1.0"
chrono = "0.4.19"
chrono-tz = "0.6.1"
clap = { version = "3.2.5", features = ["derive", "env"] }
dyn-clone = "1.0.6"
enum_dispatch = "0.3.8"
enum_extract = "0.1.1"
futures = "0.3.21"
futures-util = "0.3.21"
headers = "0.3.7"
http = "0.2.8"
itertools = "0.10.3"
jwtk = "0.2.3"
lz4 = "1.23.3"
metrics = "0.19.0"
naive-cityhash = "0.2.0"
nom = "7.1.1"
num = "0.4.0"
num_cpus = "1.13.1"
octocrab = "0.16.0"
once_cell = "1.12.0"
opendal = { git = "https://github.com/sundy-li/opendal", rev = "a1f69bc", features = ["retry", "compress"] }
opensrv-clickhouse = "0.1.0"
opensrv-mysql = "0.1.0"
openssl = { version = "0.10.40", features = ["vendored"] }
parking_lot = "0.12.1"
paste = "1.0.7"
petgraph = "0.6.2"
poem = { version = "1.3.31", features = ["rustls", "multipart", "compression"] }
primitive-types = "0.11.1"
prost = "0.10.4"
rand = "0.8.5"
regex = "1.5.6"
reqwest = "0.11.11"
rsa = "0.5.0"
segment-tree = "2.0.0"
semver = "1.0.10"
sentry = "0.27.0"
serde = { version = "1.0.137", features = ["derive"] }
serde-bridge = "0.0.3"
serde_json = "1.0.81"
serde_repr = "0.1.8"
serfig = "0.0.2"
sha1 = "0.10.1"
sha2 = "0.10.2"
smallvec = { version = "1.8.0", features = ["write"] }
snailquote = "0.3.1"
strum = "0.24.1"
strum_macros = "0.24.0"
tempfile = { version = "3.3.0", optional = true }
thiserror = "1.0.31"
threadpool = "1.8.1"
thrift = { version = "0.15.0", optional = true }
time = "0.3.10"
tokio-rustls = "0.23.4"
tokio-stream = { version = "0.1.9", features = ["net"] }
tonic = "0.7.2"
tracing = "0.1.35"
tracing-appender = "0.2.2"
twox-hash = "1.6.3"
typetag = "0.1.8"
uuid = { version = "1.1.2", features = ["serde", "v4"] }
walkdir = "2.3.2"

[dev-dependencies]
clickhouse-driver = { git = "https://github.com/datafuse-extras/clickhouse_driver", rev = "cf978da" }
criterion = "0.3.5"
goldenfile = "1.4"
hex = "0.4.3"
jwt-simple = "0.11.0"
maplit = "1.0.2"
mysql_async = "0.30.0"
pretty_assertions = "1.2.1"
reqwest = { version = "0.11.11", features = ["json", "native-tls"] }
temp-env = "0.2.0"
tempfile = "3.3.0"
toml = { version = "0.5.9", default-features = false }
url = "2.2.2"
wiremock = "0.5.13"

[build-dependencies]
common-building = { path = "../common/building" }

[[bench]]
name = "bench_main"
harness = false
