[package]
name = "databend-storages-common-table-meta"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[dependencies]
databend-common-arrow = { path = "../../../../common/arrow" }
databend-common-base = { path = "../../../../common/base" }
databend-common-datavalues = { path = "../../../datavalues" }
databend-common-exception = { path = "../../../../common/exception" }
databend-common-expression = { path = "../../../expression" }
databend-common-io = { path = "../../../../common/io" }

async-backtrace = { workspace = true }
async-trait = { workspace = true }
bincode = "1.3.3"
chrono = { workspace = true }
enum-as-inner = "0.5"
futures = { workspace = true }
futures-util = { workspace = true }
rand = "0.8.3"
rmp-serde = "1.1.1"
serde = { workspace = true }
serde_json = { workspace = true }
snap = { version = "1.1.0", optional = true }
typetag = { workspace = true }
zstd = "0.12.3"

[dev-dependencies]
criterion = "0.4"
databend-common-storages-fuse = { path = "../../fuse" }
pot = "2.0.0"

[features]
dev = ["snap"]

[[bench]]
name = "bench"
harness = false
required-features = ["dev"]
