name: "Setup BendSQL"
description: "Setup BendSQL for CI"
inputs:
  version:
    description: "bendsql version"
    required: false
    default: v0.3.7
runs:
  using: "composite"
  steps:
    - name: Download and Install
      shell: bash
      run: |
        curl -fsSLo ./bendsql.tar.gz https://github.com/databendcloud/bendsql/releases/download/${{ inputs.version }}/bendsql-linux-amd64.tar.gz
        tar -xvzf ./bendsql.tar.gz
        chmod +x ./linux-amd64/bendsql
        sudo cp ./linux-amd64/bendsql /usr/local/bin/bendsql
        bendsql version
