name: Benchmark (trusted)

on:
  workflow_run:
    workflows: ["Benchmark"]
    types:
      - completed
  workflow_call:
    inputs:
      tag:
        description: The tag to run benchmark
        required: true
        type: string

permissions:
  id-token: write
  pull-requests: write
  contents: read

env:
  BENCHMARK_S3_PREFIX: s3://repo.databend.rs/benchmark/clickbench

jobs:
  metadata:
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_call'
    runs-on: [self-hosted, X64, Linux, dev]
    outputs:
      sha: ${{ steps.metadata.outputs.sha }}
      run_id: ${{ steps.metadata.outputs.run_id }}
      source: ${{ steps.metadata.outputs.source }}
      source_id: ${{ steps.metadata.outputs.source_id }}
    steps:
      - uses: actions/checkout@v3
      - name: Download benchmark metadata
        id: metadata
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          case ${{ github.event_name }} in
            # pull request
            workflow_run)
              gh run download ${{ github.event.workflow_run.id }} --name benchmark-metadata
              echo "sha=$(jq -r '.sha' metadata.json)" >> $GITHUB_OUTPUT
              echo "run_id=$(jq -r '.run_id' metadata.json)" >> $GITHUB_OUTPUT
              echo "source=pr" >> $GITHUB_OUTPUT
              echo "source_id=$(jq -r '.pr_id' metadata.json)" >> $GITHUB_OUTPUT
              ;;
            workflow_call)
              echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT
              echo "run_id=${{ github.run_id }}" >> $GITHUB_OUTPUT
              echo "source=release" >> $GITHUB_OUTPUT
              echo "source_id=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "Unknown event name: ${{ github.event_name }}"
              exit 1
              ;;
          esac

  local:
    needs: metadata
    timeout-minutes: 30
    runs-on: [self-hosted, X64, Linux, perf]
    strategy:
      matrix:
        dataset:
          - hits
          - tpch
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup_bendsql
      - name: Download artifact
        run: |
          mkdir -p ./target/release
          case ${{ needs.metadata.outputs.source }} in
            pr)
              aws s3 sync s3://databend-ci/release/${{ needs.metadata.outputs.sha }}/x86_64-unknown-linux-gnu/default/ \
                target/release/ --exclude "*" --include "databend-*" --no-progress
              ;;
            release)
              version=${{ needs.metadata.outputs.source_id }}
              target=x86_64-unknown-linux-gnu
              aws s3 cp s3://repo.databend.rs/databend/${version}/databend-${version}-${target}.tar.gz distro/
              tar x -C ./target/release -f ./distro/databend-${version}-${target}.tar.gz --strip-components 1 bin/
              ;;
            *)
              echo "Unknown source: ${{ needs.metadata.outputs.source }}"
              exit 1
              ;;
          esac
          chmod +x ./target/release/databend-*
      - name: Setup Databend Binary
        shell: bash
        run: |
          sudo cp ./target/release/databend-* /usr/local/bin/
          databend-query --version
          databend-meta --version
      - uses: ./.github/actions/benchmark_local
        with:
          sha: ${{ needs.metadata.outputs.sha }}
          run_id: ${{ needs.metadata.outputs.run_id }}
          dataset: ${{ matrix.dataset }}
          source: ${{ needs.metadata.outputs.source }}
          source_id: ${{ needs.metadata.outputs.source_id }}

  docker:
    needs: metadata
    timeout-minutes: 10
    runs-on: [self-hosted, X64, Linux, dev]
    outputs:
      tag: ${{ steps.prepare.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        run: |
          mkdir -p ./target/release
          case ${{ needs.metadata.outputs.source }} in
            pr)
              aws s3 sync s3://databend-ci/release/${{ needs.metadata.outputs.sha }}/x86_64-unknown-linux-gnu/default/ \
                target/release/ --exclude "*" --include "databend-*" --no-progress
              ;;
            release)
              version=${{ needs.metadata.outputs.source_id }}
              target=x86_64-unknown-linux-gnu
              wget -P distro -qc https://repo.databend.rs/databend/${version}/databend-${version}-${target}.tar.gz
              tar x -C ./target/release -f ./distro/databend-${version}-${target}.tar.gz --strip-components 1 bin/
              ;;
            *)
              echo "Unknown source: ${{ needs.metadata.outputs.source }}"
              exit 1
              ;;
          esac
          chmod +x ./target/release/databend-*
      - name: Prepare docker build
        run: |
          mkdir -p ./distro/linux/amd64
          cp ./target/release/databend-* ./distro/linux/amd64
      - uses: ./.github/actions/setup_docker
        id: login
        with:
          repo: databend-query
          ecr_role_arn: ${{ secrets.ECR_ROLE_ARN }}
      - name: Prepare for docker
        id: prepare
        run: |
          mkdir -p ./distro/linux/amd64
          cp ./target/release/databend-query ./distro/linux/amd64/databend-query
          echo "tag=benchmark-${{ needs.metadata.outputs.sha }}" >> $GITHUB_OUTPUT
      - name: push service image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.login.outputs.ecr_repo }}:${{ steps.prepare.outputs.tag }}
          platforms: linux/amd64
          context: .
          file: ./docker/debian/query.Dockerfile

  cloud:
    needs: [metadata, docker]
    timeout-minutes: 60
    runs-on: [self-hosted, X64, Linux, dev]
    strategy:
      matrix:
        dataset:
          - hits
          - tpch
        size:
          - Medium
      fail-fast: true
      max-parallel: 1
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup_bendsql
      - uses: ./.github/actions/benchmark_cloud
        with:
          sha: ${{ needs.metadata.outputs.sha }}
          run_id: ${{ needs.metadata.outputs.run_id }}
          dataset: ${{ matrix.dataset }}
          source: ${{ needs.metadata.outputs.source }}
          source_id: ${{ needs.metadata.outputs.source_id }}
          size: ${{ matrix.size }}
          image_tag: ${{ needs.docker.outputs.tag }}
          cloud_email: ${{ secrets.BENCHMARK_CLOUD_EMAIL }}
          cloud_password: ${{ secrets.BENCHMARK_CLOUD_PASSWORD }}
          cloud_org: ${{ secrets.BENCHMARK_CLOUD_ORG }}
          cloud_endpoint: ${{ secrets.BENCHMARK_CLOUD_ENDPOINT }}

  comment_on_pr:
    runs-on: [self-hosted, X64, Linux, dev]
    needs: [metadata, local, cloud]
    if: needs.metadata.outputs.source == 'pr'
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.REPO_ROLE_ARN }}
          role-duration-seconds: 900
          aws-region: us-east-2
      - uses: actions/download-artifact@v3
        with:
          name: benchmark-hits-local
          path: benchmark/clickbench/results/hits
      - uses: actions/download-artifact@v3
        with:
          name: benchmark-hits-cloud-Medium
          path: benchmark/clickbench/results/hits
      - uses: actions/download-artifact@v3
        with:
          name: benchmark-hits-local
          path: benchmark/clickbench/results/tpch
      - uses: actions/download-artifact@v3
        with:
          name: benchmark-tpch-cloud-Medium
          path: benchmark/clickbench/results/tpch
      - name: Get Report Prefix
        run: |
          echo "REPORT_S3_PREFIX=${{ env.BENCHMARK_S3_PREFIX }}/pr/${{ needs.metadata.outputs.source_id }}/${{ needs.metadata.outputs.run_id }}" >> $GITHUB_ENV
          echo "REPORT_URL_PREFIX=https://repo.databend.rs/benchmark/clickbench/pr/${{ needs.metadata.outputs.source_id }}/${{ needs.metadata.outputs.run_id }}" >> $GITHUB_ENV
      - name: Upload PR clickbench result to repo.databend.rs
        working-directory: benchmark/clickbench
        run: |
          aws s3 cp ./results/hits/result-hits-local.json ${{ env.REPORT_S3_PREFIX }}/hits-local.json
          aws s3 cp ./results/hits/result-hits-cloud-Medium.json ${{ env.REPORT_S3_PREFIX }}/hits-cloud-Medium.json
          aws s3 cp ./results/tpch/result-tpch-local.json ${{ env.REPORT_S3_PREFIX }}/tpch-local.json
          aws s3 cp ./results/tpch/result-tpch-cloud-Medium.json ${{ env.REPORT_S3_PREFIX }}/tpch-cloud-Medium.json
      - name: Get latest release clickbench result
        working-directory: benchmark/clickbench
        run: |
          aws s3 sync "${{ env.BENCHMARK_S3_PREFIX }}/release/hits/latest/" ./results/hits/
          aws s3 sync "${{ env.BENCHMARK_S3_PREFIX }}/release/tpch/latest/" ./results/tpch/
      - name: Generate clickbench report
        working-directory: benchmark/clickbench
        run: |
          ./update-results.sh hits
          ./update-results.sh tpch
      - name: Upload PR clickbench report to repo.databend.rs
        working-directory: benchmark/clickbench
        run: |
          aws s3 cp ./results/hits.html ${{ env.REPORT_S3_PREFIX }}/hits.html
          aws s3 cp ./results/tpch.html ${{ env.REPORT_S3_PREFIX }}/tpch.html
      - name: Comment on PR
        uses: everpcpc/comment-on-pr-action@v1
        with:
          number: ${{ needs.metadata.outputs.source_id }}
          token: ${{ github.token }}
          body: |
            ![local](https://img.shields.io/static/v1?label=AWS%20EC2&message=c5.4xlarge&color=orange&logo=amazonec2)
            ![cloud](https://img.shields.io/static/v1?label=DatabendCloud&message=Medium&color=blue&logo=icloud)
            ## ClickBench Report
            * **hits**: ${{ env.REPORT_URL_PREFIX }}/hits.html
            * **tpch**: ${{ env.REPORT_URL_PREFIX }}/tpch.html

  archive_for_release:
    runs-on: [self-hosted, X64, Linux, dev]
    needs: [metadata, local, cloud]
    if: needs.metadata.outputs.source == 'release'
    strategy:
      matrix:
        dataset:
          - "tpch"
          - "hits"
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.REPO_ROLE_ARN }}
          role-duration-seconds: 900
          aws-region: us-east-2
      - uses: actions/download-artifact@v3
        with:
          name: benchmark-hits-local
          path: benchmark/clickbench/results/hits
      - uses: actions/download-artifact@v3
        with:
          name: benchmark-hits-cloud-Medium
          path: benchmark/clickbench/results/hits
      - uses: actions/download-artifact@v3
        with:
          name: benchmark-hits-local
          path: benchmark/clickbench/results/tpch
      - uses: actions/download-artifact@v3
        with:
          name: benchmark-tpch-cloud-Medium
          path: benchmark/clickbench/results/tpch
      - name: Upload nightly results to repo.databend.rs
        working-directory: benchmark/clickbench
        run: |
          RESULT_PEFIX="${{ env.BENCHMARK_S3_PREFIX }}/release/${{ matrix.dataset }}/$(date -u +%Y)/$(date -u +%m)/$(date -u +%Y-%m-%d)/${{ needs.metadata.outputs.source_id }}"
          LATEST_PREFIX="${{ env.BENCHMARK_S3_PREFIX }}/release/${{ matrix.dataset }}/latest/latest"
          aws s3 cp ./results/result-${{ matrix.dataset }}-local.json "${RESULT_PEFIX}-local.json"
          aws s3 cp ./results/result-${{ matrix.dataset }}-cloud-Medium.json "${RESULT_PEFIX}-cloud-Medium.json"
          aws s3 cp ./results/result-${{ matrix.dataset }}-local.json "${LATEST_PREFIX}-local.json"
          aws s3 cp ./results/result-${{ matrix.dataset }}-cloud-Medium.json "${LATEST_PREFIX}-cloud-Medium.json"
          rm -f ./results/result-*
      - name: Generate report
        working-directory: benchmark/clickbench
        run: |
          ./update-results.sh ${{ matrix.dataset }}
      - name: Upload PR clickbench report to repo.databend.rs
        working-directory: benchmark/clickbench
        run: |
          aws s3 cp ./results/${{ matrix.dataset }}.html ${{ env.BENCHMARK_S3_PREFIX }}/release/${{ matrix.dataset }}.html
